Shoppingcart/Models/CodeFirst/cartitem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Shoppingcart.Models.CodeFirst
{
    public class cartitem
    {
        public int ID { get; set; }
        public int Itemid { get; set; }
        public int Count { get; set; }
        public DateTime Creationdate { get; set; }
        public string CustomerID { get; set; }

        public virtual Item Item { get; set; }
        public virtual ApplicationUser Customer { get; set; }

        public decimal? UnitTotal
        {
            get
            {
                return Count * Item.Price;
            }  
        }
    }
}

Shoppingcart/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Shoppingcart.Models;
using Shoppingcart.Models.CodeFirst;
using System.IO;

namespace Shoppingcart.Controllers
{
    public class ItemsController : Universal
    {
        

        // GET: Items
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "ID,CreationDate,UpdatedDate,Name,Price,MediaURL,Description")] Item item, HttpPostedFileBase image)
        {
            if(image != null && image.ContentLength > 0)
            {
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpg" && ext != ".gif" && ext != ".bmp")
                {
                    ModelState.AddModelError("image", "Invalid Format.");
                }

            }
            if (ModelState.IsValid)
            {
                var filePath = "/Assets/Images/";
                var absPath = Server.MapPath("~" + filePath);
                item.MediaURL = filePath + image.FileName;
                image.SaveAs(Path.Combine(absPath, image.FileName));
                item.CreationDate = System.DateTime.Now;
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Items/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "ID,CreationDate,UpdatedDate,Name,Price,MediaURL,Description")] Item item, string mediaURL, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpg" && ext != ".gif" && ext != ".bmp")
                {
                    ModelState.AddModelError("image", "Invalid Format.");
                }

            }


            if (ModelState.IsValid)
            {

                if (image != null)

                {
                    var filePath = "/Assets/Images/"; //relative server path          
                    var absPath = Server.MapPath("~" + filePath); // path on physicaldrive on server   
                    item.MediaURL = filePath + image.FileName; // media url for relative path             
                    image.SaveAs(Path.Combine(absPath, image.FileName)); //save image} 
                }
                else
                {
                    item.MediaURL = mediaURL;
                }
                db.Entry(item).State = EntityState.Modified;
                item.UpdatedDate = System.DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            var absPath = Server.MapPath("~" + item.MediaURL);
            System.IO.File.Delete(absPath);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Shoppingcart/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Shoppingcart.Models;
using Shoppingcart.Models.CodeFirst;
using Microsoft.AspNet.Identity;

namespace Shoppingcart.Controllers
{
    [Authorize]
    public class OrdersController : Universal
    {
        [Authorize]
        // GET: Orders
        public ActionResult Index()
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var orders = db.Order.AsNoTracking().Where(c => c.CustomerId == user.Id).ToList();
            return View(orders);
        }
        [Authorize]
        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }
        [Authorize]
        // GET: Orders/Create

        public ActionResult Create()
        {
            return View();
        }
        [Authorize]
        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create([Bind(Include ="Address,City,State,Zipcode,Country,Phone")]Order order)
         
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var CartItems = db.Cartitem.Where(c => c.CustomerID == user.Id).ToList();
            if (ModelState.IsValid)
            {
                order.Completed = true;
                order.CustomerId = user.Id;
                order.OrderDate = DateTime.Now;
                order.Total = ViewBag.carttotal;
                db.Order.Add(order);
                db.SaveChanges();
                
                foreach (var cartItem in user.Cartitem.ToList())
                {
                    OrderItem orderItem = new OrderItem();
                    orderItem.ItemId = cartItem.Itemid;
                    orderItem.OrderId = order.ID;
                    orderItem.Quantity = cartItem.Count;
                    orderItem.UnitPrice = cartItem.Item.Price;
                    db.OrderItems.Add(orderItem);
                    db.Cartitem.Remove(cartItem);
                    db.SaveChanges();
                }
              
                return RedirectToAction("Details", new { id = order.ID });
            }

            return View(order);
        }

        // GET: Orders/Edit/5
    
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Order order = db.Order.Find(id);
        //    if (order == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(order);
        //}

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
      
        //public ActionResult Edit([Bind(Include = "ID,Address,City,State,Zipcode,Country,Phone,Total,OrderDate,CustomerId,Completed")] Order order)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        db.Entry(order).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(order);
        //}

        // GET: Orders/Delete/5
    
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Order order = db.Order.Find(id);
        //    if (order == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(order);
        //}

        // POST: Orders/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
      
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Order order = db.Order.Find(id);
        //    db.Order.Remove(order);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Shoppingcart/Controllers/cartitemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Shoppingcart.Models;
using Shoppingcart.Models.CodeFirst;
using Microsoft.AspNet.Identity;

namespace Shoppingcart.Controllers
{
    [Authorize]
    public class cartitemsController : Universal
    {


        // GET: cartitems
        public ActionResult Index()
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            return View(user.Cartitem.ToList());
        }

        // GET: cartitems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cartitem cartitem = db.Cartitem.Find(id);
            if (cartitem == null)
            {
                return HttpNotFound();
            }
            return View(cartitem);
        }

        // GET: cartitems/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}



        // POST: cartitems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(int? itemId)
        {
            if (itemId != null)
            {
                var user = db.Users.Find(User.Identity.GetUserId());
                if (user == null)
                {
                    return RedirectToAction("Login","Account");
                }
                if (db.Cartitem.Where(c => c.CustomerID == user.Id).Any(c => c.Itemid == itemId))
                {
                    var existingItem = db.Cartitem.Where(c => c.CustomerID == user.Id).FirstOrDefault(c => c.Itemid == itemId);
                    existingItem.Count += 1;
                    db.SaveChanges();
                }
                else
                {
                    cartitem cart = new cartitem();
                    cart.Itemid = (int)itemId;
                    cart.CustomerID = user.Id;
                    cart.Count = 1;
                    cart.Creationdate = DateTime.Now;
                    db.Cartitem.Add(cart);
                    db.SaveChanges();
                }
                
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }



        // GET: cartitems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cartitem cartitem = db.Cartitem.Find(id);
            if (cartitem == null)
            {
                return HttpNotFound();
            }
            return View(cartitem);
        }

        // POST: cartitems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Itemid,Count,Creationdate,CustomerID")] cartitem cartitem)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(cartitem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cartitem);
        }

        // GET: cartitems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cartitem cartitem = db.Cartitem.Find(id);
            if (cartitem == null)
            {
                return HttpNotFound();
            }
            return View(cartitem);
        }

        // POST: cartitems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            cartitem cartitem = db.Cartitem.Find(id);
            db.Cartitem.Remove(cartitem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Shoppingcart/Views/cartitems/Create.cshtml
@model Shoppingcart.Models.CodeFirst.cartitem

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>cartitem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Itemid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Itemid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Itemid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Creationdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Creationdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Creationdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Shoppingcart/Views/cartitems/Delete.cshtml
@model Shoppingcart.Models.CodeFirst.cartitem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>cartitem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Itemid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Itemid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Count)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Creationdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Creationdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Shoppingcart/Views/cartitems/Details.cshtml
@model Shoppingcart.Models.CodeFirst.cartitem

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>cartitem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Itemid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Itemid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Count)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Creationdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Creationdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Shoppingcart/Views/cartitems/Edit.cshtml
@model Shoppingcart.Models.CodeFirst.cartitem

@{
    ViewBag.Title = "Edit";
}

<h2 style="color:#f5f5f5">Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 style="color:#f5f5f5">cartitem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Creationdate)
        @Html.HiddenFor(model => model.Itemid)
        @Html.HiddenFor(model => model.CustomerID)

       

        <div class="form-group" style="color:#f5f5f5">
            @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control", min="1" } })
                @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
   <a href="@Url.Action("Index","cartitems")" class="btn btn-danger" > Back To Cart!</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Shoppingcart/Views/cartitems/Index.cshtml
@model IEnumerable<Shoppingcart.Models.CodeFirst.cartitem>

@{
    ViewBag.Title = "Index";
}

<h2 style="color:#f5f5f5" >Index</h2>

<p >
 <a href="@Url.Action("Index", "Items")"style="color:#f5f5f5">Click Here To Add Another Item!</a>
</p>
<table class="table">
    <tr>
        <th style="color:#f5f5f5">
            Item
        </th>
        <th style="color:#f5f5f5">
            @Html.DisplayNameFor(model => model.Count)
        </th>
        <th style="color:#f5f5f5">
            @Html.DisplayNameFor(model => model.Creationdate)
        </th>
        <th style="color:#f5f5f5">
        @Html.DisplayNameFor(model => model.Item.Price)
        </th>
        <th style="color:#f5f5f5">
            @Html.DisplayNameFor(model => model.UnitTotal)
        </th>
        <th></th>
        <th></th>
    </tr>

    @{decimal p = 0;}
    
    @foreach (var item in Model)
    {
        <tr>
            
            <td style="color:#f5f5f5">
                @Html.DisplayFor(modelItem => item.Item.Name)
            </td>
            <td style="color:#f5f5f5">
                @Html.DisplayFor(modelItem => item.Count)
                &nbsp;
                <a href="@Url.Action("Edit", "cartitems", new { id = item.ID })" style="color:#FF533D">Change Quanity!</a>
            </td>
            <td style="color:#f5f5f5">
                @Html.DisplayFor(modelItem => item.Creationdate)
            </td>
            <td style="color:#f5f5f5">
                @Html.DisplayFor(modelItem => item.Item.Price) 
                @{p += item.Item.Price;}
            </td>
            <td style="color:#f5f5f5">
                @Html.DisplayFor(modelItem =>item.UnitTotal)
             
            </td>
            <td>
                <img src="@Url.Content(item.Item.MediaURL)" />
            </td>
            <td>
           <a href="@Url.Action("Details", "Items", new { id = item.Item.ID }, null )" class="btn btn-info"> Details</a> |
             <a href="@Url.Action("Delete","cartitems")" class="btn btn-danger" > Delete</a>   
                
            </td>

        </tr>
           
       
    }
       

</table>
<div @*style="margin-left:50%"*@>
    <hr />
<h3 style="color:#f5f5f5">Total Price</h3>
<p style="color:#f5f5f5;font-size:23px;">$ @ViewBag.carttotal </p>
</div>
@if (ViewBag.carttotal > 0)
{

    <a href="@Url.Action("Create", "Orders")" style="color:#f5f5f5;font-size:medium;border:none;" class="btn btn-danger">Checkout Here!</a>
}
else
{

<a href="@Url.Action("Index", "Items")" style="color:#f5f5f5;background-color:#FF533D" class="btn btn-default">Please Select a Item to buy!</a>
    }