Shoppingcart/Models/CodeFirst/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Shoppingcart.Models.CodeFirst
{
    public class Order
    {
        public int ID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public decimal Total { get; set; }
        public DateTime OrderDate { get; set; }
        public string CustomerId { get; set; }
        public bool Completed { get; set; }

        public virtual ApplicationUser Customer { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    

    }
}

Shoppingcart/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Shoppingcart.Models;
using Shoppingcart.Models.CodeFirst;
using System.IO;

namespace Shoppingcart.Controllers
{
    public class ItemsController : Universal
    {
        

        // GET: Items
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "ID,CreationDate,UpdatedDate,Name,Price,MediaURL,Description")] Item item, HttpPostedFileBase image)
        {
            if(image != null && image.ContentLength > 0)
            {
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpg" && ext != ".gif" && ext != ".bmp")
                {
                    ModelState.AddModelError("image", "Invalid Format.");
                }

            }
            if (ModelState.IsValid)
            {
                var filePath = "/Assets/Images/";
                var absPath = Server.MapPath("~" + filePath);
                item.MediaURL = filePath + image.FileName;
                image.SaveAs(Path.Combine(absPath, image.FileName));
                item.CreationDate = System.DateTime.Now;
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Items/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "ID,CreationDate,UpdatedDate,Name,Price,MediaURL,Description")] Item item, string mediaURL, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpg" && ext != ".gif" && ext != ".bmp")
                {
                    ModelState.AddModelError("image", "Invalid Format.");
                }

            }


            if (ModelState.IsValid)
            {

                if (image != null)

                {
                    var filePath = "/Assets/Images/"; //relative server path          
                    var absPath = Server.MapPath("~" + filePath); // path on physicaldrive on server   
                    item.MediaURL = filePath + image.FileName; // media url for relative path             
                    image.SaveAs(Path.Combine(absPath, image.FileName)); //save image} 
                }
                else
                {
                    item.MediaURL = mediaURL;
                }
                db.Entry(item).State = EntityState.Modified;
                item.UpdatedDate = System.DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            var absPath = Server.MapPath("~" + item.MediaURL);
            System.IO.File.Delete(absPath);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Shoppingcart/Controllers/OrderItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Shoppingcart.Models;
using Shoppingcart.Models.CodeFirst;
using Microsoft.AspNet.Identity;

namespace Shoppingcart.Controllers
{
    public class OrderItemsController : Universal
    {
        

        //// GET: OrderItems
        //public ActionResult Index()
        //{
        //    return View(db.OrderItems.ToList());
        //}

        //// GET: OrderItems/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    OrderItem orderItem = db.OrderItems.Find(id);
        //    if (orderItem == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(orderItem);
        //}

        //// GET: OrderItems/Create
   
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: OrderItems/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID,OrderId,ItemId,Quantity,UnitPrice")] OrderItem orderItem)
        //{
        //    var user = db.Users.Find(User.Identity.GetUserId());
        //    var Orders = db.Order.Where(c => c.CustomerId == user.Id).ToList();
        //    if (ModelState.IsValid)
        //    {

        //        orderItem.Quantity = Orders.Count;
        //        orderItem.ID = orderItem.Order.ID;
        //        //orderItem.OrderId = orderItem.Order. ;
        //        //orderItem.UnitPrice = ;
        //        db.OrderItems.Add(orderItem);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(orderItem);
        //}

        //// GET: OrderItems/Edit/5
      
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    OrderItem orderItem = db.OrderItems.Find(id);
        //    if (orderItem == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(orderItem);
        //}

        //// POST: OrderItems/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
   
        //public ActionResult Edit([Bind(Include = "ID,OrderId,ItemId,Quantity,UnitPrice")] OrderItem orderItem)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(orderItem).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(orderItem);
        //}

        //// GET: OrderItems/Delete/5
       
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    OrderItem orderItem = db.OrderItems.Find(id);
        //    if (orderItem == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(orderItem);
        //}

        //// POST: OrderItems/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
       
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    OrderItem orderItem = db.OrderItems.Find(id);
        //    db.OrderItems.Remove(orderItem);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Shoppingcart/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Shoppingcart.Models;
using Shoppingcart.Models.CodeFirst;
using Microsoft.AspNet.Identity;

namespace Shoppingcart.Controllers
{
    [Authorize]
    public class OrdersController : Universal
    {
        [Authorize]
        // GET: Orders
        public ActionResult Index()
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var orders = db.Order.AsNoTracking().Where(c => c.CustomerId == user.Id).ToList();
            return View(orders);
        }
        [Authorize]
        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }
        [Authorize]
        // GET: Orders/Create

        public ActionResult Create()
        {
            return View();
        }
        [Authorize]
        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create([Bind(Include ="Address,City,State,Zipcode,Country,Phone")]Order order)
         
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var CartItems = db.Cartitem.Where(c => c.CustomerID == user.Id).ToList();
            if (ModelState.IsValid)
            {
                order.Completed = true;
                order.CustomerId = user.Id;
                order.OrderDate = DateTime.Now;
                order.Total = ViewBag.carttotal;
                db.Order.Add(order);
                db.SaveChanges();
                
                foreach (var cartItem in user.Cartitem.ToList())
                {
                    OrderItem orderItem = new OrderItem();
                    orderItem.ItemId = cartItem.Itemid;
                    orderItem.OrderId = order.ID;
                    orderItem.Quantity = cartItem.Count;
                    orderItem.UnitPrice = cartItem.Item.Price;
                    db.OrderItems.Add(orderItem);
                    db.Cartitem.Remove(cartItem);
                    db.SaveChanges();
                }
              
                return RedirectToAction("Details", new { id = order.ID });
            }

            return View(order);
        }

        // GET: Orders/Edit/5
    
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Order order = db.Order.Find(id);
        //    if (order == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(order);
        //}

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
      
        //public ActionResult Edit([Bind(Include = "ID,Address,City,State,Zipcode,Country,Phone,Total,OrderDate,CustomerId,Completed")] Order order)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        db.Entry(order).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(order);
        //}

        // GET: Orders/Delete/5
    
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Order order = db.Order.Find(id);
        //    if (order == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(order);
        //}

        // POST: Orders/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
      
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Order order = db.Order.Find(id);
        //    db.Order.Remove(order);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Shoppingcart/Views/Orders/Create.cshtml
@model Shoppingcart.Models.CodeFirst.Order

@{
    ViewBag.Title = "Create";
}

<h2 style="color:#f5f5f5">Create Order</h2>
<table class="table"style="color:#f5f5f5">
    <tr>
        <th></th>
        <th>
            Item
        </th>
        <th>
            Quantity
        </th>
        <th>
            Unit Price
        </th>
        <th>
            Unit Total
        </th>
        <th></th>
    </tr>

    @foreach (var item in ViewBag.CartItems)
    {
        <tr style="color:#f5f5f5">
            <td>
                <img src="@item.Item.MediaURL" style="max-width: 100px" />
            </td>
            <td>
                @item.Item.Name
            </td>
            <td>
                @item.Count
            </td>
            <td>
                @item.Item.Price
            </td>
            <td>
                @item.UnitTotal
            </td>
           
        </tr>
    }

</table>
<hr />
<h1 style="color:#f5f5f5">$ @ViewBag.carttotal</h1>
<hr />
<div>
    <a href="@Url.Action("Index","Items")" class="btn btn-default" style="color:#f5f5f5;background-color:#FF533D">Click Here to add More items to your Cart!</a>
</div>
&nbsp;



<div class="jumbotron" style="background-color:#FF533D">
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.CustomerId)
    @Html.HiddenFor(model => model.OrderDate)
    @Html.HiddenFor(model => model.Total)
    @Html.HiddenFor(model => model.Completed)

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="color:#f5f5f5">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:#f5f5f5">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:#f5f5f5">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:#f5f5f5">
            @Html.LabelFor(model => model.Zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zipcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zipcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:#f5f5f5">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="color:#f5f5f5">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>





   
    


        <div class="form-group"style="color:#f5f5f5">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Purchase" class="btn btn-default" />
            </div>
        </div>
    </div>
    
}
    </div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Shoppingcart/Views/Orders/Delete.cshtml
@model Shoppingcart.Models.CodeFirst.Order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zipcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Completed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Completed)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Shoppingcart/Views/Orders/Details.cshtml
@model Shoppingcart.Models.CodeFirst.Order

@{
    ViewBag.Title = "Details";
}

<h2 style="color:#f5f5f5">Thanks You For Ordering!</h2>

<div class="jumbotron" style="background-color:#FF533D">
    <h4 style="color:#f5f5f5">Heres Your Details</h4>
    <hr />
    <dl class="dl-horizontal" style="color:#f5f5f5">
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zipcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Completed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Completed)
        </dd>

    </dl>
    <table class="table"style="color:#f5f5f5">
        <tr>
            <th></th>
            <th>
                Item
            </th>
            <th>
                Quantity
            </th>
            <th>
                Unit Price
            </th>
            <th>
                Unit Total
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.OrderItems)
        {
            <tr style="color:#f5f5f5">
                <td>
                    <img src="@item.Item.MediaURL" style="max-width: 100px"/>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Item.Name)
                   
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitPrice)
                </td>
                <td>
                    @{ 
                        var unitTotal = item.UnitPrice * item.Quantity;
                    }
                    @unitTotal
                </td>
                <td>
                    <a href="@Url.Action("Details","Items", new { id = item.ItemId })" class="btn btn-info">Details</a>
                </td>
            </tr>
        }

    </table>
</div>
<p class="btn btn-danger" style="border:none;color:#f5f5f5">
    <a href="@Url.Action("Index","Items")" style="color:#f5f5f5">Order Again!</a>
   
   
</p>
<a href="@Url.Action("Index","Orders")" class="btn btn-info">See Order History</a>

Shoppingcart/Views/Orders/Index.cshtml
@model IEnumerable<Shoppingcart.Models.CodeFirst.Order>

@{
    ViewBag.Title = "Index";
}

<h2 style="color:#f5f5f5">Index</h2>


<table class="table" style="color:#f5f5f5">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zipcode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Completed)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr >
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Zipcode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Completed)
        </td>
        <td>
           @*<a href @Url.Action("Details","OrderItems", new {id = item.ID }) style="color:#f5f5f5">Click Here to see your Ordered Items!</a>*@
        </td>
        <td>
            
           <a href="@Url.Action("Details", "Orders", new { id=item.ID })" class="btn btn-danger" > Cart Details</a> 
           
        </td>
    </tr>
}

</table>
@*<a href="@Url.Action("","")"*@